// Kratki pregledi cjelina — prozor koji se otvori klikom na cjelinu u izborniku Lessons.
// Uređuje se ručno (ne generira ga osvjezi.js).
//   h  = naslov (stranica 1)
//   s  = jedna kratka rečenica ispod naslova (nije obavezno)
//   ex = 1–2 primjera [hrvatski, engleski] (stranica 1, nije obavezno)
//   p2 = stranica 2, popis blokova:
//        { t: [[hr, en], ...] }       tablica: hrvatski lijevo, prijevod desno
//        { g: [[zaglavlje...], [redak...], ...] }  mala mreža, prvi redak je zaglavlje
//              (gh: [0, 2] = koji su retci zaglavlja, ako ih je više)
//        { w: [[hr, en], ...] }       riječi u jednom retku
// Broj koraka, prag i trajanje testa prozor čita iz data.js.
window.PREGLEDI = {
  // ---------- 1 ----------
  'Lesson 1': { h: 'Your first Croatian sentences',
    ex: [['Kava je dobra.', 'The coffee is good.'], ['More je plavo.', 'The sea is blue.']],
    p2: [{ t: [['Grad je velik.', 'The city is big.'], ['Kuća je velika.', 'The house is big.'], ['More je veliko.', 'The sea is big.']] },
         { w: [['kuća', 'house'], ['grad', 'city'], ['more', 'sea'], ['kava', 'coffee']] }] },
  'Vocabulary 1': { h: 'Things, colours and sizes', s: 'About 40 everyday words.',
    p2: [{ w: [['soba', 'room'], ['stol', 'table'], ['knjiga', 'book']] },
         { w: [['crven', 'red'], ['plav', 'blue'], ['žut', 'yellow']] },
         { w: [['velik', 'big'], ['mali', 'small'], ['nov', 'new']] }] },
  'Grammar 1': { h: 'Endings that match',
    ex: [['Kuća je velika.', 'The house is big.'], ['Kava nije dobra.', "The coffee isn't good."]],
    p2: [{ g: [['grad', 'kuća', 'more'], ['velik', 'velika', 'veliko']] },
         { w: [['je', 'is'], ['nije', "isn't"]] }] },
  'Practice 1': { h: 'Read your first texts', s: 'A city, a room and a café.',
    p2: [{ t: [['Kava, molim.', 'A coffee, please.'], ['Izvolite.', 'Here you are.'], ['Hvala!', 'Thank you!']] }] },
  'Test 1': { h: 'Show what you know', s: 'Words, endings and simple sentences.',
    p2: [{ g: [['grad', 'kuća', 'more'], ['star', 'stara', 'staro']] },
         { w: [['je', 'is'], ['nije', "isn't"]] }] },

  // ---------- 2 ----------
  'Lesson 2': { h: 'Talking about people',
    ex: [['Ja sam studentica.', 'I am a student.'], ['Ona je visoka.', 'She is tall.']],
    p2: [{ t: [['Ja sam Ana.', 'I am Ana.'], ['Ti si Marko.', 'You are Marko.'], ['Oni su veseli.', 'They are cheerful.']] },
         { w: [['ja', 'I'], ['ti', 'you'], ['on', 'he'], ['ona', 'she']] }] },
  'Vocabulary 2': { h: 'Jobs, countries, character', s: 'People words and your first greetings.',
    p2: [{ w: [['kuhar', 'cook'], ['vozač', 'driver'], ['učitelj', 'teacher']] },
         { w: [['Hrvat', 'Croat'], ['Talijan', 'Italian'], ['Nijemac', 'German']] },
         { t: [['Kako si?', 'How are you?'], ['Dobro sam.', "I'm fine."]] }] },
  'Grammar 2': { h: 'The verb "to be"',
    ex: [['Mi smo turisti.', 'We are tourists.'], ['Nisam gladan.', "I'm not hungry."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['sam', 'si', 'je'], ['mi', 'vi', 'oni'], ['smo', 'ste', 'su']], gh: [0, 2] }] },
  'Practice 2': { h: 'Meet new people', s: 'Introductions, a café and a team.',
    p2: [{ t: [['Tko si ti?', 'Who are you?'], ['Kako ste?', 'How are you?'], ['Dobro sam, hvala.', "I'm fine, thanks."]] }] },
  'Test 2': { h: 'Show what you know', s: 'People, "to be" and introductions.',
    p2: [{ g: [['on', 'ona', 'oni'], ['visok', 'visoka', 'visoki']] },
         { w: [['sam', 'I am'], ['smo', 'we are'], ['su', 'they are']] }] },

  // ---------- 3 ----------
  'Lesson 3': { h: 'Things you do',
    ex: [['Pijem čaj.', "I'm drinking tea."], ['Ana radi.', 'Ana is working.']],
    p2: [{ t: [['čitam', 'I read'], ['čitaš', 'you read'], ['čita', 'he / she reads']] },
         { w: [['piti', 'drink'], ['jesti', 'eat'], ['raditi', 'work'], ['spavati', 'sleep']] }] },
  'Vocabulary 3': { h: 'Everyday verbs', s: 'Verbs and the things that go with them.',
    p2: [{ w: [['čitati', 'read'], ['pisati', 'write'], ['piti', 'drink']] },
         { w: [['kruh', 'bread'], ['sir', 'cheese'], ['čaj', 'tea']] },
         { w: [['uvijek', 'always'], ['često', 'often'], ['nikad', 'never']] }] },
  'Grammar 3': { h: 'The present tense',
    ex: [['Učim hrvatski.', "I'm learning Croatian."], ['Ne pijem sok.', "I'm not drinking juice."]],
    p2: [{ g: [['čitati', 'raditi', 'pisati'], ['čitam', 'radim', 'pišem'], ['čitaš', 'radiš', 'pišeš'], ['čita', 'radi', 'piše']] }] },
  'Practice 3': { h: 'A day of actions', s: 'A flat, an evening and a quiet Sunday.',
    p2: [{ t: [['Što radiš?', 'What are you doing?'], ['Učim hrvatski.', "I'm learning Croatian."], ['Gledam film.', "I'm watching a film."]] }] },
  'Test 3': { h: 'Show what you know', s: 'Everyday verbs in the present.',
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['pijem', 'piješ', 'pije']] },
         { w: [['ne pijem', "I don't drink"]] }] },

  // ---------- 4 ----------
  'Lesson 4': { h: 'The family',
    ex: [['Tata kuha, a brat uči.', 'Dad cooks, my brother studies.'], ['Mama radi i čita.', 'Mum works and reads.']],
    p2: [{ t: [['i', 'and'], ['a', 'and, while'], ['ali', 'but']] },
         { w: [['mama', 'mum'], ['tata', 'dad'], ['brat', 'brother'], ['sestra', 'sister']] }] },
  'Vocabulary 4': { h: 'Family and home', s: 'Close family, wider family and new verbs.',
    p2: [{ w: [['mama', 'mum'], ['tata', 'dad'], ['baka', 'grandma']] },
         { w: [['brat', 'brother'], ['sestra', 'sister'], ['dijete', 'child']] },
         { w: [['imati', 'have'], ['kuhati', 'cook'], ['živjeti', 'live']] }] },
  'Grammar 4': { h: 'Joining sentences',
    ex: [['Mama radi i čita.', 'Mum works and reads.'], ['Ne plivam jer je hladno.', "I'm not swimming because it's cold."]],
    p2: [{ t: [['i', 'and'], ['a', 'and, while'], ['ali', 'but'], ['jer', 'because']] }] },
  'Practice 4': { h: 'Family life', s: 'A family, a busy morning and Saturday at home.',
    p2: [{ t: [['Ovo je obitelj.', 'This is a family.'], ['Što radiš danas?', 'What are you doing today?'], ['Baka kuha.', 'Grandma is cooking.']] }] },
  'Test 4': { h: 'Show what you know', s: 'Family words, verbs and joining words.',
    p2: [{ t: [['i', 'and'], ['a', 'and, while'], ['ali', 'but'], ['jer', 'because']] }] },

  // ---------- 5 ----------
  'Lesson 5': { h: 'Shopping',
    ex: [['Pijem kavu.', "I'm drinking coffee."], ['Trebate li vrećicu?', 'Do you need a bag?']],
    p2: [{ t: [['Kava je dobra.', 'The coffee is good.'], ['Pijem kavu.', "I'm drinking coffee."], ['Jedem jabuku.', "I'm eating an apple."]] },
         { w: [['kruh', 'bread'], ['voda', 'water'], ['sir', 'cheese'], ['riba', 'fish']] }] },
  'Vocabulary 5': { h: 'Shopping and food', s: 'Market words and 10 new verbs.',
    p2: [{ w: [['voda', 'water'], ['juha', 'soup'], ['riža', 'rice']] },
         { w: [['kruh', 'bread'], ['mlijeko', 'milk'], ['meso', 'meat']] },
         { w: [['kupovati', 'buy'], ['trebati', 'need'], ['plaćati', 'pay']] }] },
  'Grammar 5': { h: 'Your first case',
    ex: [['Kupujem svježu salatu.', "I'm buying fresh lettuce."], ['Idem u trgovinu.', "I'm going to the shop."]],
    p2: [{ g: [['kava', 'crna kava'], ['Pijem kavu.', 'Pijem crnu kavu.']] },
         { w: [['u trgovinu', 'to the shop'], ['na tržnicu', 'to the market']] }] },
  'Practice 5': { h: 'At the market', s: 'A market, a note on the fridge and breakfast.',
    p2: [{ t: [['Ana kupuje jabuku.', 'Ana is buying an apple.'], ['Trebamo kruh i rižu.', 'We need bread and rice.'], ['Volim kavu!', 'I love coffee!']] }] },
  'Test 5': { h: 'Show what you know', s: 'Food, shopping and your first case.',
    p2: [{ g: [['kava', 'juha', 'salata'], ['kavu', 'juhu', 'salatu']] },
         { w: [['kruh', 'bread (no change)']] }] },

  // ---------- 6 ----------
  'Lesson 6': { h: 'In the city',
    ex: [['Vidim prijatelja.', 'I see a friend.'], ['Čekam tramvaj.', "I'm waiting for the tram."]],
    p2: [{ t: [['Vidim prijatelja.', 'I see a friend.'], ['Vidim tramvaj.', 'I see a tram.'], ['Vidim psa.', 'I see a dog.']] },
         { w: [['ulica', 'street'], ['trg', 'square'], ['most', 'bridge']] }] },
  'Vocabulary 6': { h: 'The city and traffic', s: 'People, transport and places in town.',
    p2: [{ w: [['tramvaj', 'tram'], ['vlak', 'train'], ['bicikl', 'bike']] },
         { w: [['ulica', 'street'], ['trg', 'square'], ['most', 'bridge']] },
         { w: [['vidjeti', 'see'], ['čuti', 'hear'], ['voziti', 'drive']] }] },
  'Grammar 6': { h: 'People and things',
    ex: [['Čekam prijatelja.', "I'm waiting for a friend."], ['Vidim ga.', 'I see him.']],
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['me', 'me'], ['te', 'you'], ['ga', 'him'], ['je', 'her']] }] },
  'Practice 6': { h: 'City life', s: 'A tram ride, a busy street and a lost dog.',
    p2: [{ t: [['Ana čeka tramvaj.', 'Ana is waiting for the tram.'], ['Tramvaj je pun.', 'The tram is full.'], ['Oprostite!', 'Excuse me!']] }] },
  'Test 6': { h: 'Show what you know', s: 'The city and the whole first case.',
    p2: [{ g: [['kava', 'prijatelj', 'tramvaj'], ['kavu', 'prijatelja', 'tramvaj']] },
         { w: [['ga', 'him, it'], ['je', 'her']] }] },

  // ---------- 7 ----------
  'Lesson 7': { h: 'At school: more than one',
    ex: [['Knjige su nove.', 'The books are new.'], ['Učenici pjevaju.', 'The pupils are singing.']],
    p2: [{ g: [['učenik', 'knjiga', 'pismo'], ['učenici', 'knjige', 'pisma']] },
         { w: [['škola', 'school'], ['olovka', 'pencil'], ['ispit', 'exam']] }] },
  'Vocabulary 7': { h: 'School and songs', s: 'School words, plurals and 10 new verbs.',
    p2: [{ w: [['škola', 'school'], ['olovka', 'pencil'], ['torba', 'bag']] },
         { w: [['ispit', 'exam'], ['ocjena', 'grade'], ['zadaća', 'homework']] },
         { w: [['pjevati', 'sing'], ['igrati', 'play'], ['znati', 'know']] }] },
  'Grammar 7': { h: 'The plural',
    ex: [['Stolovi su stari.', 'The tables are old.'], ['Djeca pjevaju.', 'The children are singing.']],
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['čitamo', 'čitate', 'čitaju']] }] },
  'Practice 7': { h: 'School days', s: 'A school, a timetable, a choir and new pupils.',
    p2: [{ t: [['Dobro jutro, djeco!', 'Good morning, children!'], ['Djeca pjevaju.', 'The children are singing.'], ['Knjige su nove.', 'The books are new.']] }] },
  'Test 7': { h: 'Show what you know', s: 'Plural nouns, adjectives and verbs.',
    p2: [{ g: [['grad', 'škola', 'selo'], ['gradovi', 'škole', 'sela']] },
         { g: [['mi', 'vi', 'oni'], ['pjevamo', 'pjevate', 'pjevaju']] }] },

  // ---------- 8 ----------
  'Lesson 8': { h: 'Summer plans',
    ex: [['Plivat ću.', 'I will swim.'], ['Mi ćemo putovati.', 'We will travel.']],
    p2: [{ t: [['Plivat ću.', 'I will swim.'], ['Putovat ćemo u subotu.', 'We will travel on Saturday.'], ['Neću plivati.', "I won't swim."]] },
         { w: [['plaža', 'beach'], ['otok', 'island'], ['sutra', 'tomorrow']] }] },
  'Vocabulary 8': { h: 'Plans and travel', s: 'Holidays, days, clothes and 10 new verbs.',
    p2: [{ w: [['plaža', 'beach'], ['otok', 'island'], ['kofer', 'suitcase']] },
         { w: [['sutra', 'tomorrow'], ['vikend', 'weekend'], ['tjedan', 'week']] },
         { w: [['putovati', 'travel'], ['plivati', 'swim'], ['letjeti', 'fly']] }] },
  'Grammar 8': { h: 'The future',
    ex: [['Sutra ću plivati.', 'Tomorrow I will swim.'], ['Neću raditi.', "I won't work."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['ću', 'ćeš', 'će'], ['mi', 'vi', 'oni'], ['ćemo', 'ćete', 'će']], gh: [0, 2] }] },
  'Practice 8': { h: 'Plans and journeys', s: 'A summer plan, a packing list and a train ticket.',
    p2: [{ t: [['Ići ćemo u Split.', 'We will go to Split.'], ['Ustat ću rano.', 'I will get up early.'], ['Tata će voziti.', 'Dad will drive.']] }] },
  'Test 8': { h: 'Show what you know', s: 'Plans, travel and the future.',
    p2: [{ t: [['Plivat ću.', 'I will swim.'], ['Ja ću plivati.', 'I will swim.'], ['Neću plivati.', "I won't swim."]] }] },

  // ---------- 9 ----------
  'Lesson 9': { h: 'Sport and hobbies',
    ex: [['Moj hobi je fotografija.', 'My hobby is photography.'], ['Boli me koljeno.', 'My knee hurts.']],
    p2: [{ t: [['moj dres', 'my jersey'], ['moja lopta', 'my ball'], ['moje koljeno', 'my knee']] },
         { w: [['glava', 'head'], ['ruka', 'arm'], ['noga', 'leg'], ['srce', 'heart']] }] },
  'Vocabulary 9': { h: 'Sport, body and "my"', s: 'Sport words, the body and whose it is.',
    p2: [{ w: [['klub', 'club'], ['trener', 'coach'], ['igrač', 'player']] },
         { w: [['glava', 'head'], ['ruka', 'arm'], ['noga', 'leg']] },
         { w: [['moj', 'my'], ['tvoj', 'your'], ['naš', 'our']] }] },
  'Grammar 9': { h: 'Mine, yours, ours',
    ex: [['njegova gitara', 'his guitar'], ['Marko voli svoju sestru.', 'Marko loves his own sister.']],
    p2: [{ g: [['moj', 'moja', 'moje'], ['njegov', 'njegova', 'njegovo'], ['njezin', 'njezina', 'njezino']] },
         { w: [['svoj', 'my / his / her own'], ['čiji', 'whose']] }] },
  'Practice 9': { h: 'Our club, my hobby', s: 'A hobby, a lost ball and a football club.',
    p2: [{ t: [['Je li ovo tvoja lopta?', 'Is this your ball?'], ['Da, moja je!', "Yes, it's mine!"], ['Naš klub je mali.', 'Our club is small.']] }] },
  'Test 9': { h: 'Show what you know', s: 'Possessives, sport and the body.',
    p2: [{ g: [['dres', 'lopta', 'koljeno'], ['moj', 'moja', 'moje']] },
         { w: [['svoj', 'my / his / her own']] }] },

  // ---------- 10 ----------
  'Lesson 10': { h: 'Yesterday',
    ex: [['Gledao sam film.', 'I watched a film.'], ['Bilo je savršeno.', 'It was perfect.']],
    p2: [{ t: [['On je gledao.', 'He watched.'], ['Ona je gledala.', 'She watched.'], ['Oni su gledali.', 'They watched.']] },
         { w: [['jučer', 'yesterday'], ['sinoć', 'last night']] }] },
  'Vocabulary 10': { h: 'Yesterday and free time', s: 'Films, time words and phrases for stories.',
    p2: [{ w: [['serija', 'series'], ['komedija', 'comedy'], ['kazalište', 'theatre']] },
         { w: [['jučer', 'yesterday'], ['sinoć', 'last night'], ['nedavno', 'recently']] },
         { t: [['Kako je bilo?', 'How was it?'], ['Bilo je super!', 'It was great!']] }] },
  'Grammar 10': { h: 'The past tense',
    ex: [['Jučer sam gledao film.', 'Yesterday I watched a film.'], ['Nisam imao vremena.', "I didn't have time."]],
    p2: [{ g: [['on', 'ona', 'oni'], ['gledao', 'gledala', 'gledali'], ['bio', 'bila', 'bili']] },
         { w: [['sam', 'I (did)'], ['nisam', "I didn't"]] }] },
  'Practice 10': { h: 'Last weekend', s: 'A lazy Saturday, the seaside and a family weekend.',
    p2: [{ t: [['Gdje si bio jučer?', 'Where were you yesterday?'], ['Bio sam na moru.', 'I was at the seaside.'], ['Plivao sam.', 'I swam.']] }] },
  'Test 10': { h: 'Show what you know', s: 'The past tense and free time.',
    p2: [{ g: [['on', 'ona', 'oni'], ['bio je', 'bila je', 'bili su']] },
         { w: [['nisam', "I wasn't / didn't"]] }] },

  // ---------- 11 ----------
  'Lesson 11': { h: 'Asking questions',
    ex: [['Što kupuješ?', 'What are you buying?'], ['Koliko košta?', 'How much is it?']],
    p2: [{ t: [['Gdje živiš?', 'Where do you live?'], ['Voliš li kavu?', 'Do you like coffee?'], ['Lijepo je, zar ne?', "It's nice, isn't it?"]] },
         { w: [['jedan', '1'], ['pet', '5'], ['deset', '10'], ['dvadeset', '20']] }] },
  'Vocabulary 11': { h: 'Questions and numbers', s: 'Question words, numbers and birthdays.',
    p2: [{ w: [['tko', 'who'], ['što', 'what'], ['gdje', 'where']] },
         { w: [['kada', 'when'], ['zašto', 'why'], ['koliko', 'how much']] },
         { w: [['pet', 'five'], ['deset', 'ten'], ['sto', 'a hundred']] }] },
  'Grammar 11': { h: 'Three ways to ask',
    ex: [['Kada dolaziš?', 'When are you coming?'], ['Voliš li kavu? — Volim.', 'Do you like coffee? — I do.']],
    p2: [{ t: [['Gdje si?', 'Where are you?'], ['Jesi li umoran?', 'Are you tired?'], ['Umoran si, zar ne?', "You're tired, right?"]] },
         { w: [['koji', 'which'], ['kakav', 'what kind'], ['čiji', 'whose']] }] },
  'Practice 11': { h: 'The present mystery', s: 'A birthday present, a mystery box and a quiz.',
    p2: [{ t: [['Za koga?', 'For whom?'], ['Tko je poslao poklon?', 'Who sent the present?'], ['Sretan rođendan!', 'Happy birthday!']] }] },
  'Test 11': { h: 'Show what you know', s: 'Questions, numbers and prices.',
    p2: [{ t: [['Koliko košta?', 'How much is it?'], ['Koliko godina imaš?', 'How old are you?'], ['Imam dvadeset godina.', "I'm twenty."]] }] },

  // ---------- 12 ----------
  'Lesson 12': { h: 'Saying no',
    ex: [['Ništa ne jedem.', "I'm not eating anything."], ['Nikad ne pijem mlijeko.', 'I never drink milk.']],
    p2: [{ t: [['nisam', 'I am not'], ['nemam', "I don't have"], ['neću', "I won't"]] },
         { w: [['ništa', 'nothing'], ['nitko', 'nobody'], ['nikad', 'never']] }] },
  'Vocabulary 12': { h: "Food we (don't) like", s: 'Food, tastes and eating out.',
    p2: [{ w: [['piletina', 'chicken'], ['gljive', 'mushrooms'], ['palačinke', 'pancakes']] },
         { w: [['slan', 'salty'], ['kiseo', 'sour'], ['ljut', 'spicy']] },
         { t: [['Dobar tek!', 'Enjoy your meal!'], ['Račun, molim.', 'The bill, please.']] }] },
  'Grammar 12': { h: 'Negation',
    ex: [['Nitko ne kuha.', 'Nobody is cooking.'], ['Ne pijem kavu, nego čaj.', "I don't drink coffee, but tea."]],
    p2: [{ t: [['nešto → ništa', 'something → nothing'], ['netko → nitko', 'somebody → nobody'], ['nekad → nikad', 'sometimes → never']] },
         { w: [['još ne', 'not yet'], ['više ne', 'no longer']] }] },
  'Practice 12': { h: 'The picky eaters', s: 'Soup, a restaurant and a child who eats nothing.',
    p2: [{ t: [['Ne volim juhu.', "I don't like soup."], ['Imate li ribu?', 'Do you have fish?'], ['Nažalost, nemamo.', "Sorry, we don't."]] }] },
  'Test 12': { h: 'Show what you know', s: 'Saying no, and food.',
    p2: [{ t: [['Ništa ne jedem.', "I'm not eating anything."], ['Nemam vremena.', "I don't have time."], ['Neću doći.', "I won't come."]] }] },

  // ---------- 13 ----------
  'Lesson 13': { h: 'Where are you?',
    ex: [['Ja sam u gradu.', "I'm in town."], ['Ana je u školi.', 'Ana is at school.']],
    p2: [{ t: [['Idem u grad.', "I'm going to town."], ['Ja sam u gradu.', "I'm in town."]] },
         { w: [['pošta', 'post office'], ['kuhinja', 'kitchen'], ['gore', 'upstairs']] }] },
  'Vocabulary 13': { h: 'Places and home', s: 'Places in town, rooms and furniture.',
    p2: [{ w: [['pošta', 'post office'], ['ljekarna', 'pharmacy'], ['luka', 'harbour']] },
         { w: [['kuhinja', 'kitchen'], ['kupaonica', 'bathroom'], ['hodnik', 'hall']] },
         { w: [['gore', 'up'], ['dolje', 'down'], ['tamo', 'there']] }] },
  'Grammar 13': { h: 'The locative',
    ex: [['Radim u uredu.', 'I work in an office.'], ['Pričam o tebi.', "I'm talking about you."]],
    p2: [{ g: [['grad', 'kino', 'škola'], ['u gradu', 'u kinu', 'u školi']] },
         { w: [['u banci', 'in the bank'], ['o meni', 'about me']] }] },
  'Practice 13': { h: 'Around town', s: 'A neighbourhood, a phone call and a family chat.',
    p2: [{ t: [['Gdje si?', 'Where are you?'], ['U autobusu sam.', "I'm on the bus."], ['Još sam u uredu.', "I'm still at the office."]] }] },
  'Test 13': { h: 'Show what you know', s: 'Where people and things are.',
    p2: [{ g: [['grad', 'more', 'škola'], ['u gradu', 'na moru', 'u školi']] }] },

  // ---------- 14 ----------
  'Lesson 14': { h: 'Giving presents',
    ex: [['Mami kupujem šal.', "I'm buying Mum a scarf."], ['Pomažem bratu.', "I'm helping my brother."]],
    p2: [{ t: [['mama → mami', 'to Mum'], ['tata → tati', 'to Dad'], ['brat → bratu', 'to my brother']] },
         { w: [['paket', 'package'], ['igračka', 'toy'], ['razglednica', 'postcard']] }] },
  'Vocabulary 14': { h: 'Giving and receivers', s: 'Gifts, receivers and December words.',
    p2: [{ w: [['igračka', 'toy'], ['ogrlica', 'necklace'], ['kišobran', 'umbrella']] },
         { w: [['davati', 'give'], ['slati', 'send'], ['donijeti', 'bring']] },
         { w: [['Božić', 'Christmas'], ['snijeg', 'snow'], ['poruka', 'message']] }] },
  'Grammar 14': { h: 'The dative',
    ex: [['Baka mi šalje paket.', 'Grandma is sending me a package.'], ['Meni, ne tebi!', 'To me, not to you!']],
    p2: [{ g: [['me', 'you', 'him', 'her'], ['mi', 'ti', 'mu', 'joj']] },
         { w: [['Komu?', 'To whom?']] }] },
  'Practice 14': { h: 'December gifts', s: 'Presents, a postman and a card from Grandma.',
    p2: [{ t: [['Komu pišeš?', 'Who are you writing to?'], ['Pišem baki.', "I'm writing to Grandma."], ['Sretan Božić!', 'Merry Christmas!']] }] },
  'Test 14': { h: 'Show what you know', s: 'Giving to someone, and being somewhere.',
    p2: [{ t: [['Dajem mami cvijeće.', 'I give Mum flowers.'], ['Mama je u kuhinji.', 'Mum is in the kitchen.']] }] },

  // ---------- 15 ----------
  'Lesson 15': { h: 'Going out',
    ex: [['Idem s Markom.', "I'm going with Marko."], ['Idemo vlakom.', "We're going by train."]],
    p2: [{ t: [['s bratom', 'with my brother'], ['sa sestrom', 'with my sister'], ['tramvajem', 'by tram']] },
         { w: [['zabava', 'party'], ['večera', 'dinner'], ['izlazak', 'night out']] }] },
  'Vocabulary 15': { h: 'Going out and weather', s: 'A night out, transport and the weather.',
    p2: [{ w: [['zabava', 'party'], ['večera', 'dinner'], ['ples', 'dance']] },
         { w: [['trajekt', 'ferry'], ['skuter', 'scooter'], ['pješice', 'on foot']] },
         { w: [['kiša', 'rain'], ['vjetar', 'wind'], ['oblak', 'cloud']] }] },
  'Grammar 15': { h: 'The instrumental',
    ex: [['Pišem olovkom.', 'I write with a pencil.'], ['Idem s tobom.', "I'm going with you."]],
    p2: [{ g: [['brat', 'sestra', 'prijatelj'], ['bratom', 'sestrom', 'prijateljem']] },
         { w: [['sa mnom', 'with me'], ['s tobom', 'with you']] }] },
  'Practice 15': { h: 'Friday night', s: 'Going out, a train ride and a café menu.',
    p2: [{ t: [['S kim ideš?', 'Who are you going with?'], ['Sa sestrom.', 'With my sister.'], ['Kava s mlijekom', 'Coffee with milk']] }] },
  'Test 15': { h: 'Show what you know', s: 'Four cases, one word.',
    p2: [{ t: [['Vidim mamu.', 'I see Mum.'], ['Pišem mami.', "I'm writing to Mum."], ['Pričam o mami.', "I'm talking about Mum."], ['Idem s mamom.', "I'm going with Mum."]] }] },

  // ---------- 16 ----------
  'Lesson 16': { h: "Grandma's house",
    ex: [['Kava bez šećera.', 'Coffee without sugar.'], ['Nema problema!', 'No problem!']],
    p2: [{ t: [['kod bake', "at Grandma's"], ['iz Zagreba', 'from Zagreb'], ['pokraj kuće', 'next to the house']] },
         { w: [['vrt', 'garden'], ['vrata', 'door'], ['miris', 'smell']] }] },
  'Vocabulary 16': { h: 'House and home', s: 'Home words and little words for places.',
    p2: [{ w: [['miris', 'smell'], ['boja', 'colour'], ['slika', 'picture']] },
         { w: [['bez', 'without'], ['iz', 'from'], ['kod', 'at']] },
         { w: [['ispred', 'in front of'], ['iza', 'behind'], ['ispod', 'under']] }] },
  'Grammar 16': { h: 'The genitive',
    ex: [['kuća moje bake', "my grandma's house"], ['Dvije kave, molim.', 'Two coffees, please.']],
    p2: [{ g: [['grad', 'kava', 'noć'], ['grada', 'kave', 'noći']] },
         { w: [['jedna kava', 'one coffee'], ['pet kava', 'five coffees']] }] },
  'Practice 16': { h: 'The road to the sea', s: "Grandma's house, a café and a drive to the coast.",
    p2: [{ t: [['Pokraj kuće je vrt.', 'Next to the house is a garden.'], ['Jedan čaj za Marka.', 'One tea for Marko.'], ['Putujemo iz Zagreba.', "We're travelling from Zagreb."]] }] },
  'Test 16': { h: 'Show what you know', s: 'The genitive and the home.',
    p2: [{ g: [['grad', 'baka', 'more'], ['iz grada', 'kod bake', 'do mora']] }] },

  // ---------- 17 ----------
  'Lesson 17': { h: 'Giving orders',
    ex: [['Uzmi tri jaja.', 'Take three eggs.'], ['Skrenite lijevo.', 'Turn left.']],
    p2: [{ t: [['Gledaj!', 'Look!'], ['Uzmi!', 'Take!'], ['Pij!', 'Drink!']] },
         { w: [['lijevo', 'left'], ['desno', 'right'], ['ravno', 'straight on']] }] },
  'Vocabulary 17': { h: 'Recipes and directions', s: 'Kitchen words, commands and directions.',
    p2: [{ w: [['brašno', 'flour'], ['tava', 'pan'], ['ulje', 'oil']] },
         { w: [['uzmi', 'take'], ['dodaj', 'add'], ['miješaj', 'mix']] },
         { w: [['lijevo', 'left'], ['desno', 'right'], ['ravno', 'straight on']] }] },
  'Grammar 17': { h: 'The imperative',
    ex: [['Gledajte!', 'Look! (all of you)'], ['Možeš li mi pomoći?', 'Can you help me?']],
    p2: [{ g: [['ti', 'vi', "let's"], ['gledaj', 'gledajte', 'gledajmo']] },
         { w: [['mogu', 'I can'], ['moram', 'I must'], ['hoću', 'I want']] }] },
  'Practice 17': { h: 'Recipes and directions', s: 'Pancakes, finding the station and a strict coach.',
    p2: [{ t: [['Gdje je kolodvor?', 'Where is the station?'], ['Idite ravno.', 'Go straight on.'], ['Pij vodu!', 'Drink water!']] }] },
  'Test 17': { h: 'Show what you know', s: 'Commands, recipes and directions.',
    p2: [{ g: [['ti', 'vi'], ['gledaj', 'gledajte'], ['uzmi', 'uzmite'], ['pij', 'pijte']] }] },

  // ---------- 18 ----------
  'Lesson 18': { h: 'A million euros',
    ex: [['Kupio bih kuću.', 'I would buy a house.'], ['Htjela bih kavu.', "I'd like a coffee."]],
    p2: [{ t: [['Kupio bih...', 'I would buy... (he)'], ['Kupila bih...', 'I would buy... (she)'], ['Biste li mogli...?', 'Could you...?']] },
         { w: [['san', 'dream'], ['sreća', 'happiness'], ['ako', 'if']] }] },
  'Vocabulary 18': { h: 'Wishes and feelings', s: 'Dreams, feelings and "would".',
    p2: [{ w: [['san', 'dream'], ['jahta', 'yacht'], ['vila', 'villa']] },
         { w: [['sreća', 'happiness'], ['strah', 'fear'], ['nada', 'hope']] },
         { w: [['sanjati', 'dream'], ['nadati se', 'hope'], ['bojati se', 'fear']] }] },
  'Grammar 18': { h: 'The conditional',
    ex: [['Išli bismo na more.', 'We would go to the sea.'], ['Ne bih žurila.', "I wouldn't hurry."]],
    p2: [{ g: [['ja', 'ti', 'on / ona'], ['bih', 'bi', 'bi'], ['mi', 'vi', 'oni'], ['bismo', 'biste', 'bi']], gh: [0, 2] }] },
  'Practice 18': { h: 'Dreams and perfect days', s: 'Lottery dreams, a perfect day and a street survey.',
    p2: [{ t: [['Prvo bih kupio kuću.', "First I'd buy a house."], ['Svaki dan bih plivala.', "I'd swim every day."], ['Što biste radili?', 'What would you do?']] }] },
  'Test 18': { h: 'Show what you know', s: 'Wishes, dreams and feelings.',
    p2: [{ g: [['he', 'she'], ['kupio bih', 'kupila bih'], ['htio bih', 'htjela bih']] }] },

  // ---------- 19 ----------
  'Lesson 19': { h: 'Verb twins',
    ex: [['Pisao sam pismo.', 'I was writing a letter.'], ['Napisao sam pismo.', 'I finished the letter.']],
    p2: [{ t: [['pisati → napisati', 'write → finish writing'], ['piti → popiti', 'drink → drink up'], ['čitati → pročitati', 'read → read it all']] },
         { w: [['dugo', 'for long'], ['napokon', 'finally'], ['odmah', 'at once']] }] },
  'Vocabulary 19': { h: 'Stories and events', s: 'Verb pairs, time words and story words.',
    p2: [{ t: [['učiti → naučiti', 'study → learn'], ['kupovati → kupiti', 'shop → buy']] },
         { w: [['napokon', 'finally'], ['odjednom', 'suddenly'], ['već', 'already']] }] },
  'Grammar 19': { h: 'Finished or not?',
    ex: [['Ana je učila cijelu večer.', 'Ana studied all evening.'], ['Naučila je sve.', 'She learned everything.']],
    p2: [{ g: [['going on', 'finished'], ['pisati', 'napisati'], ['piti', 'popiti'], ['kupovati', 'kupiti']] }] },
  'Practice 19': { h: 'The letter', s: 'A long letter, homework and a Saturday list.',
    p2: [{ t: [['Jesi li napisao zadaću?', 'Did you finish your homework?'], ['Skoro!', 'Almost!'], ['Napokon!', 'Finally!']] }] },
  'Test 19': { h: 'Show what you know', s: 'Verb pairs: going on or finished.',
    p2: [{ g: [['going on', 'finished'], ['pisati', 'napisati'], ['čitati', 'pročitati'], ['raditi', 'napraviti']] }] },

  // ---------- 20 ----------
  'Lesson 20': { h: 'Big sentences',
    ex: [['Ostajem doma jer pada kiša.', "I'm staying in because it's raining."], ['Ako je sunčano, idemo van.', "If it's sunny, we'll go out."]],
    p2: [{ t: [['jer', 'because'], ['kad', 'when'], ['ako', 'if'], ['iako', 'although']] },
         { w: [['koji', 'which, who'], ['da', 'that']] }] },
  'Vocabulary 20': { h: 'Memories and big sentences', s: 'Joining words, summer memories and learning.',
    p2: [{ w: [['jer', 'because'], ['kad', 'when'], ['ako', 'if']] },
         { w: [['dok', 'while'], ['iako', 'although'], ['kao', 'like']] },
         { w: [['uspomena', 'memory'], ['otok', 'island'], ['galeb', 'seagull']] }] },
  'Grammar 20': { h: 'Complex sentences',
    ex: [['Mislim da ćeš doći.', "I think you'll come."], ['film koji gledam', "the film I'm watching"]],
    p2: [{ t: [['Kad dođeš, zovi me.', 'When you come, call me.'], ['Znam da je velik.', 'I know that it is big.']] },
         { w: [['da', 'that'], ['koji', 'which, who']] }] },
  'Practice 20': { h: 'The summer I remember', s: 'An island summer, an essay and a postcard.',
    p2: [{ t: [['Pozdrav s otoka!', 'Greetings from the island!'], ['Draga bako,', 'Dear Grandma,'], ['Učim hrvatski jer...', "I'm learning Croatian because..."]] }] },
  'Test 20': { h: 'The final test', s: 'Everything from all 20 lessons.',
    p2: [{ t: [['Učim.', "I'm learning."], ['Učio sam.', 'I learned.'], ['Učit ću.', 'I will learn.'], ['Učio bih.', 'I would learn.']] }] }
};
